ci:
  autofix_prs: true
  skip: [taplo-lint]
exclude: "^pixi.lock$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=8192]
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        # follow sources even when they aren't specified on the command line
        args: ["--external-sources"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint # makes web calls so can't be used in CI
  - repo: local
    hooks:
      - id: pixi-lock-check
        name: pixi-lock-check
        entry: bash -c "PATH=$HOME/.pixi/bin:$PATH pixi lock --check"
        stages: [pre-push]
        language: system
