name: finddata
channels:
  - conda-forge
dependencies:
  - anaconda-client
  - argcomplete
  - boa
  - conda-build < 4
  - conda-verify
  - check-wheel-contents
  - libmamba
  - libarchive
  - pre-commit
  # match what is used on rhel9
  - python=3.11
  - python-build
  - toml
  - versioningit
  - urllib3
  - plotly
