name: finddata
channels:
  - conda-forge
dependencies:
  - anaconda-client
  - argcomplete
  - boa
  - conda-build < 4
  - conda-verify
  - check-wheel-contents
  - libmamba
  - libarchive
  - python-build
  - toml
  - versioningit
  - urllib3
