#!/usr/bin/env python
import logging
import os
import sys
import urllib
import xml.dom.minidom

# finddata version
__version__ = "0.2.0"

# The endpoint for icat v4.
# List of restful web services available is at
# https://trac.sns.gov/adara/wiki/Post-Processing
BASE_URL = 'http://icat.sns.gov:8080/icat-rest-ws/'

# list of log levels
LOGLEVELS = ["DEBUG", "INFO", "WARNING"]

def __bashOptions(keyword):
    """
    Helper function to aid in bash completion.
    
    @param keyword The type of documentation to give out options for
    """
    if keyword == "instruments":
        INSTR = getInstruments()
        options = [instr.lower() for instr in INSTR]
        options.extend(INSTR)
        print " ".join(options)
    elif keyword == "loglevels":
        options = [level.lower() for level in LOGLEVELS]
        options.extend(LOGLEVELS)
        print " ".join(options)

def parseInt(number):
    try:
        return int(number)
    except ValueError, e:
        logging.info("Invalid run numbers: %s" % str(e))

    return 0

def procNumbers(numbers):
    # simply see if it is an integer
    try:
        return [int(numbers)]
    except ValueError:
        pass
    
    # split on commas
    result = []
    for item in numbers.split(','):
        # if there is a dash then it is a range
        if "-" in item:
            item = [parseInt(i) for i in item.split("-")]
            item.sort()
            if item[0]:
                result.extend(range(item[0], item[1]+1))
        else:
            item = parseInt(item)
            if item:
                result.append(item)

    return result

def procLocations(locations):
    """
    Turn a list of xml nodes into a list of paths. This only returns
    paths for files that pass os.path.exists.

    @param locations The xml node that contains the locations
    @returns The list of files. The list is empty if none are found.
    """
    logging.debug("starting with %d locations" % len(locations))
    str_locs = []

    # convert nodes to strings
    for location in locations:
        for node in location.childNodes:
            if node.nodeType == node.TEXT_NODE:
                str_locs.append(str(node.data))
                break
    logging.debug("converted %d locations to strings" % len(str_locs))

    # see what is acually readible by the user
    result = []
    for location in str_locs:
        if os.path.exists(location):
            result.append(location)
    logging.debug("%d locations exist" % len(result))

    return result

def getXml(endpoint):
    url = BASE_URL + endpoint
    logging.info("trying " + url)

    # get the document
    handle = urllib.urlopen(url)
    doc =  handle.read()
    logging.debug("DOC:" + doc)

    # parse the xml
    return xml.dom.minidom.parseString(doc)


def getInstruments():
    """
    Hit ICAT to find out the list of instruments at the facility.
    """
    doc = getXml('experiment/SNS')

    # convert to actual instruments
    instr_xml = doc.getElementsByTagName("instruments")[0]
    instr_str = []
    for instr in instr_xml.childNodes:
        for node in instr.childNodes:
            if node.nodeType == node.TEXT_NODE:
                instr_str.append(str(node.data))
                break
    logging.debug("converted %d locations to strings" % len(instr_str))
    return instr_str

def getProposal(instr, run):
    """
    Get the proposal for a given run.
    """
    doc = getXml("dataset/SNS/" + instr + '/' + str(run) + "/metaOnly")

    xmlblob = doc.getElementsByTagName("proposal")[0]
    proposal = "Failed to find proposal"
    for node in xmlblob.childNodes:
        if node.nodeType == node.TEXT_NODE:
            proposal = str(node.data)
            break

    return proposal

def getRunsInProp(instr, proposal):
    doc = getXml("experiment/SNS/" + instr + "/" + proposal)
    xmlblob = doc.getElementsByTagName("runRange")[0]
    runs = "Failed to find any runs for " + proposal
    for node in xmlblob.childNodes:
        if node.nodeType == node.TEXT_NODE:
            runs = str(node.data)
            runs = runs.replace(" ", "")
            break
    return runs

def getFileLoc(filename):
    """
    Ping ICAT for the locations that the file might be at and convert them
    into usable paths.

    @return The first path that works (as suggested by ICAT) or None.
    """
    doc = getXml('datafile/filename/' + filename)

    # convert to actual locations
    locations = doc.getElementsByTagName("locations")[0]
    locations = procLocations(locations.childNodes)

    logging.info("found locations[%d]: %s" % (len(locations), str(locations)))

    if len(locations) > 0: # always return the first one
        return locations[0]
    else:
        return None

def findfile(instr, run):
    """
    Find the specified run.
    """
    run = str(run) # should come in as an integer

    # try pre-ADARA name
    shortname = instr+"_"+run+"_event.nxs"
    filename = getFileLoc(shortname)
    if filename is None:
        logging.info("failed to find pre-ADARA file: " + shortname)
    else:
        return filename

    # try ADARA name
    shortname = instr+"_"+run+".nxs.h5"
    filename = getFileLoc(shortname)
    if filename is None:
        logging.info("failed to find ADARA file: " + shortname)
    else:
        return filename

    # give up
    raise RuntimeError("Failed to find data for %s %s" % (instr, run))

if __name__ == "__main__":
    # set up optparse
    import optparse # deprecated since v2.7 and should switch to argparse
    parser = optparse.OptionParser(description="Find data files using ICAT",
                                   usage="%prog [options] <instr> <runnumbers/proposal>")
    parser.add_option("-l", "--loglevel", dest="loglevel", default="WARNING",
                      help="Specify the log level (" \
                          + ", ".join(LOGLEVELS)+ ")")
    parser.add_option("-v", "--version", dest="version", action="store_true",
                      help="Print the version information and exit")
    parser.add_option("-f", "--filename", dest="filename",
                      help="look for a specific filename")
    parser.add_option("", "--getproposal", dest="getproposal",
                      action="store_true",
                      help="Show the proposal for the run")
    parser.add_option("", "--listruns", dest="listruns",
                      action="store_true",
                      help="List all of the runs in a proposal")

    # parse the command line
    (options, args) = parser.parse_args()

    # setup logging
    options.loglevel = options.loglevel.upper()
    options.loglevel = getattr(logging, options.loglevel.upper(),
                               logging.WARNING)
    logging.basicConfig(format='%(levelname)s:%(message)s',
                        level=options.loglevel)

    # log the options and arguments
    logging.debug('opts ' + str(options))
    logging.debug('args ' + str(args))

    # if they want the version just give it back and exit
    if options.version:
        print "finddata version " + __version__
        sys.exit(0)

    # if the filename is specified just search and be done
    if options.filename:
        filename = getFileLoc(options.filename)
        if filename is not None:
            print filename
            sys.exit(0)
        else:
            print "Failed to find file", options.filename
            sys.exit(1)

    # hidden options to help out bash completion
    if len(args) == 1 and args[0] in ["instruments", "loglevels"]:
        __bashOptions(args[0])
        sys.exit(0)

    # verify that both instrument and runnumber were supplied
    if len(args) < 2:
        msg = "Got %d argument. Expecting instrument and run number" % len(args)
        msg += " or --filename FILENAME"
        parser.error(msg)
    instr = args[0].upper()
    INSTR = getInstruments()
    if not instr in INSTR:
        parser.error("Unknown instrument '%s' %s" % (instr, str(INSTR)))
    runnumbers = []
    for arg in args[1:]:
        runnumbers.extend(procNumbers(arg))

    if len(runnumbers) <= 0:
        if not options.listruns:
            parser.error("Failed to specify run numbers")
        else:
            # is actual the proposal number
            print getRunsInProp(instr, args[1])

    # do the actual searching
    if options.getproposal:
        multiRun = (len(runnumbers) > 1)
        for run in runnumbers:
            result = getProposal(instr, run)
            if multiRun:
                print run,
            print result
    else:
        # get the file
        for run in runnumbers:
            try:
                print findfile(instr, run)
            except RuntimeError, e:
                print e
