#!/bin/bash
SRC_DIR="${PWD}"
TAR_DIR="${PWD}/tarsrc/finddata"
TAR_FILE=finddata.tar.gz

echo "creating files in ${TAR_DIR}"
mkdir -p ${TAR_DIR}
cp ${SRC_DIR}/finddata ${TAR_DIR}
cp ${SRC_DIR}/finddata.bashcomplete ${TAR_DIR}
cp ${SRC_DIR}/finddata.spec ${TAR_DIR}
cp ${SRC_DIR}/LICENSE.txt ${TAR_DIR}
cp ${SRC_DIR}/README.md ${TAR_DIR}

echo "creating tarball"
cd ${TAR_DIR}/..
tar czf ${TAR_FILE} finddata

echo "creating rpm"
rpmbuild -ta ${TAR_FILE}