#!/usr/bin/env python
from __future__ import (absolute_import, division, print_function, unicode_literals)

import json
import logging
import os
import re
import sys
try:
    from urllib2 import Request, urlopen
except ImportError:
    from urllib.request import Request, urlopen
from finddata import __version__

BASE_URL = 'https://oncat.ornl.gov/'

# basic configuration of logging
LOGLEVELS = ["DEBUG", "INFO", "WARNING"]
lower_logs = [level.lower() for level in LOGLEVELS]
LOGLEVELS.extend(lower_logs)
del lower_logs
logging.basicConfig(format='%(levelname)s:%(message)s')

########################################################################

def parseInt(number):
    try:
        return int(number)
    except ValueError as e:
        logging.info("Invalid run numbers: %s" % str(e))

    return 0

def procNumbers(numbers):
    # simply see if it is an integer
    try:
        return [int(numbers)]
    except ValueError:
        pass

    # split on commas
    result = []
    for item in numbers.split(','):
        # if there is a dash then it is a range
        if "-" in item:
            item = [parseInt(i) for i in item.split("-")]
            item.sort()
            if item[0]:
                result.extend(range(item[0], item[1]+1))
        else:
            item = parseInt(item)
            if item:
                result.append(item)

    return result

def getJson(endpoint):
    url = BASE_URL + endpoint
    req = Request(url)
    req.add_header('User-Agent', 'Finddata/' + __version__)
    handle = urlopen(req)
    if handle.getcode() != 200:
        raise RuntimeError('{} returned code={}'.format(url, handle.getcode()))
    doc = handle.read().decode()
    logging.debug("DOC:" + doc)

    return json.loads(doc)

def getInstruments(withLower=False):
    """
    Hit ONCat to find out the list of instruments at the facility.
    """
    endpoint = 'api/instruments?facility=SNS'
    doc = getJson(endpoint)
    if len(doc) == 0:
        url = BASE_URL + endpoint
        raise RuntimeError('Failed to find instruments from {}'.format(url))

    # convert to actual instruments
    instr_str = [instrument['id'] for instrument in doc]
    logging.debug("converted %d locations to strings" % len(instr_str))

    if withLower:
        lower_instr = [instr.lower() for instr in instr_str]
        instr_str.extend(lower_instr)

    return instr_str

def getProposal(instr, run):
    """
    Get the proposal for a given run.
    """
    endpoint = (
        'api/datafiles'
        '?facility=SNS'
        '&instrument=%s'
        '&ranges_q=indexed.run_number:%s'
        '&sort_by=ingested'
        '&sort_order=DESCENDING'
        '&projection=experiment'
    )
    doc = getJson(endpoint % (instr, run))
    if not doc:
        return "Failed to find proposal"

    return doc[0]['experiment']

def getRunsInProp(instr, proposal):
    endpoint = (
        'api/experiments/%s'
        '?facility=SNS'
        '&instrument=%s'
        '&projection=indexed'
    )
    doc = getJson(endpoint % (proposal, instr))

    return doc['indexed']['run_number']['ranges']

def getFileLoc(filename):
    """
    Ping ONCat for the locations that the file might be at and convert them
    into usable paths.

    @return The first path that works (as suggested by ONCat) or None.
    """
    result = re.search("^(?P<inst>.+?)_(?P<run>\d+).*$", filename)
    if not result:
        return None

    instrument = result.group('inst')
    run = result.group('run')

    endpoint = (
        'api/datafiles'
        '?facility=SNS'
        '&instrument=%s'
        '&ranges_q=indexed.run_number:%s'
        '&sort_by=ingested'
        '&sort_order=DESCENDING'
        '&projection=location'
    )
    doc = getJson(endpoint % (instrument, run))

    locations = [
        datafile['location']
        for datafile in doc
        if (
            os.path.exists(datafile['location']) and
            os.path.basename(datafile['location']).startswith(filename)
        )
    ]

    logging.info("found %s locations: [%s]" % (
        len(locations), ', '.join(locations)
    ))

    if locations: # always return the first one
        return locations[0]
    else:
        return None

def findfile(instr, run):
    """
    Find the specified run.
    """
    run = str(run) # should come in as an integer

    # try pre-ADARA name
    shortname = instr+"_"+run+"_event.nxs"
    filename = getFileLoc(shortname)
    if filename is None:
        logging.info("failed to find pre-ADARA file: " + shortname)
    else:
        return filename

    # try ADARA name
    shortname = instr+"_"+run+".nxs.h5"
    filename = getFileLoc(shortname)
    if filename is None:
        logging.info("failed to find ADARA file: " + shortname)
    else:
        return filename

    # give up
    raise RuntimeError("Failed to find data for %s %s" % (instr, run))

########################################################################

if __name__ == "__main__":
    # set up optparse
    import argparse     # for command line options
    import argcomplete  # for bash completion
    parser = argparse.ArgumentParser(description="Find data files using ICAT")

    parser.add_argument('inst', nargs='?', help='Specify the instrument name',
                        choices=getInstruments(withLower=True))
    parser.add_argument('runs', nargs='*',
                        help='Specify the run numbers')
    parser.add_argument("-l", "--loglevel", dest="loglevel", default="WARNING",
                        choices=LOGLEVELS,
                        help="Specify the log level")# (" \
                        #+ ", ".join(LOGLEVELS)+ ")")
    parser.add_argument("-v", "--version", dest="version", action="store_true",
                        help="Print the version information and exit")
    parser.add_argument("-f", "--filename", dest="filename",
                        help="look for a specific filename")
    parser.add_argument("--getproposal", dest="getproposal",
                        action="store_true",
                        help="Show the proposal for the run")
    parser.add_argument("--listruns", dest="listruns",
                        help="List all of the runs in a proposal")

    # set up bash completion
    argcomplete.autocomplete(parser)
    # parse the command line
    options = parser.parse_args()

    # setup logging
    options.loglevel = options.loglevel.upper()
    options.loglevel = getattr(logging, options.loglevel.upper(),
                               logging.WARNING)
    logging.getLogger().setLevel(options.loglevel)

    # log the options and arguments
    logging.debug('options ' + str(options))

    # if they want the version just give it back and exit
    if options.version:
        print("finddata version " + __version__)
        sys.exit(0)

    # if the filename is specified just search and be done
    if options.filename:
        filename = getFileLoc(options.filename)
        if filename is not None:
            print(filename)
            sys.exit(0)
        else:
            print("Failed to find file", options.filename)
            sys.exit(1)

    # verify that both instrument and runnumber were supplied
    if options.inst is None:
        parser.error("Must supply instrument")
    options.inst = options.inst.upper()
    INSTR = getInstruments()
    if not options.inst in INSTR:
        parser.error("Unknown instrument '%s' %s" % (options.inst, str(INSTR)))
    runnumbers = []
    for arg in options.runs:
        runnumbers.extend(procNumbers(arg))

    if options.listruns:
        # is actual the proposal number
        print(getRunsInProp(options.inst, options.listruns))
        sys.exit(0)

    if len(runnumbers) <= 0:
        parser.error('Failed to specify any runs')

    # do the actual searching
    if options.getproposal:
        multiRun = (len(runnumbers) > 1)
        for run in runnumbers:
            result = getProposal(options.inst, run)
            if multiRun:
                print(run,)
            print(result)
    else:
        # get the file
        for run in runnumbers:
            try:
                print(findfile(options.inst, run))
            except RuntimeError as e:
                print(e)
