# load information from pyproject.toml
{% set pyproject = load_file_data('pyproject.toml') %}
{% set project = pyproject.get('project', {}) %}
{% set license = project.get('license').get('text') %}
{% set description = project.get('description') %}
{% set project_url = pyproject.get('project', {}).get('urls') %}
{% set url = project_url.get('homepage') %}
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set version_number = version.split('+')[0] %}
{% set git_describe_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}

package:
  name: finddata
  version: {{ version_number }}

source:
  path: ..

build:
  noarch: python
  number: {{ git_describe_number }}
  string: py{{py}}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - versioningit
    - setuptools
    - wheel

  build:
    - setuptools
    - versioningit

  run:
    - python
    - urllib3
    - plotly

test:
  commands:
    - finddata --help

about:
  home: {{ url }}
  license: {{ license }}
  license_family: MIT
  license_file: ../LICENSE
  summary: {{ description }}
