name: Pixi Packaging and Deployment

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate versioning
          fetch-tags: true  # Fetch tags to ensure versioning works correctly
      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.47.0
          manifest-path: pyproject.toml
      - name: finddata version
        run: |
          pixi run finddata --version
      - name: build pypi package
        run: |
          pixi run build-pypi
      - name: build conda package
        run: |
          pixi run build-conda
      - name: upload conda package to anaconda
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          IS_RC: ${{ contains(github.ref, 'rc') }}
        run: |
          # label is main or rc depending on the tag-name
          CONDA_LABEL="main"
          if [ "${IS_RC}" = "true" ]; then CONDA_LABEL="rc"; fi
          echo pushing ${{ github.ref }} with label $CONDA_LABEL
          pixi run anaconda upload --label $CONDA_LABEL --user neutrons finddata-*.conda
