name: Dependency checks

on:
  workflow_dispatch:
  push:
    paths:
      - "pixi.lock"
      - "pyproject.toml"

jobs:
  security:
    runs-on: ubuntu-latest
    on:
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate versioning
          fetch-tags: true  # Fetch tags to ensure versioning works correctly
      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          manifest-path: pyproject.toml
      - name: depenency check
        run: |
          pixi run audit-deps
